
//typescript compiled enum styles:
module.exports = {
	AUTHENTICATION_FAIL: "AUTHENTICATION_FAIL",
	CODE_ERROR: "CODE_ERROR",
	DATABASE_ERROR: "DATABASE_ERROR",
	USERNAME_CONFLICT: "USERNAME_CONFLICT",
};

