
//typescript compiled enum styles:
module.exports = {
	AUTHENTICATION_FAIL: "AUTHENTICATION_FAIL",
	USERNAME_NOT_EXIST: "USERNAME_NOT_EXIST",
	USER_JOIN_ROOM_FAIL: "USER_JOIN_ROOM_FAIL",
	USERNAME_CONFLICT: "USERNAME_CONFLICT",

	CODE_ERROR: "CODE_ERROR",
	DATABASE_ERROR: "DATABASE_ERROR",
};

